services:
  - type: web
    name: shieldx-website
    env: static
    buildCommand: ""
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /shieldx.html
